name: 'Build and deploy JAR app to Azure Web App: ping-mottu-rm558763'

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      env: 
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      run: ./gradlew build
    
    - name: Find the latest JAR file
      id: find-jar
      run: echo "JAR=$(find $GITHUB_WORKSPACE/build/libs -name '*.jar' -print -quit)" >> $GITHUB_ENV

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ping-mottu'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6ab2c75d730849aeb62ee9684ecc605e }}
        package: ${{ env.JAR }}

